version: '3'
services:
  postgresql:
    image: "postgres:15.1"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    command: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:7.2.4"
    restart: always
    ports:
      - "6379:6379"