version: '3.8'

services:
  front:
    restart: always
    build:
      context: ./front
      target: prod
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`tht-visa.com`, `www.tht-visa.com`)"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
    networks:
      - app

  houston:
    restart: always
    build:
      context: ./houston
      target: prod
    environment:
      - VITE_API_URL=${VITE_API_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.houston.rule=Host(`houston.tht-visa.com`, `www.houston.tht-visa.com`)"
      - "traefik.http.routers.houston.tls=true"
      - "traefik.http.routers.houston.tls.certresolver=letsencrypt"
      - "traefik.http.services.houston.loadbalancer.server.port=4100"
    networks:
      - app

  back:
    build:
      context: ./back
      target: prod
    restart: always
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=thtvisa
      - POSTGRES_PORT=5432
      - PUBLIC_URL=${PUBLIC_URL}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - HASH_SECRET=${HASH_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.tht-visa.com`, `www.api.tht-visa.com`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=3030"
    networks:
      - app
    volumes:
      - ~/volumes/tht/uploads/:/app/uploads

  db:
    image: "postgres:alpine"
    container_name: "db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=thtvisa
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:

networks:
  app:
    external: true
