version: '3.8'

services:
  front:
    restart: always
    build:
      context: ./front
      target: prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`tht-visa.com`, `www.tht-visa.com`)"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=80"
    networks:
      - app

networks:
  app:
    external: true