version: '3.8'
services:
  postgresql:
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=thtvisa
    command: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data