version: '3.8'
services:
  db:
    image: "postgres:alpine"
    container_name: "db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=thtvisa
    command: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: