name: Build & deploy

on:
  push:
    branches: [ main, staging ]


jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          HASH_SECRET: ${{ secrets.HASH_SECRET }}
          USER_EMAIL: ${{ secrets.USER_EMAIL}}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: docker compose up --build -d

      - name: Generate .env file
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > .env

      - name: Clean up
        run: docker system prune -f